import unittest
from test_calculate_func import TestCalculateFunc
from HTMLTestRunner import HTMLTestRunner

if __name__ == '__main__':
    suite = unittest.TestSuite()

    # tests = [TestCalculateFunc("test_add"), TestCalculateFunc("test_minus"), TestCalculateFunc("test_divide")]
    # suite.addTests(tests)
    # # 直接用addTest方法添加单个TestCase
    # suite.addTest(TestCalculateFunc("test_multi"))

    # 用addTests + TestLoader
    # loadTestsFromName()，传入'模块名.TestCase名'
    # suite.addTests(unittest.TestLoader().loadTestsFromName('test_calculate_func.TestCalculateFunc'))
    # suite.addTests(unittest.TestLoader().loadTestsFromNames(['test_calculate_func.TestCalculateFunc']))

    # loadTestsFromTestCase()，传入TestCase
    suite.addTests(unittest.TestLoader().loadTestsFromTestCase(TestCalculateFunc))
    # runner = unittest.TextTestRunner(verbosity=2)
    # runner.run(suite)
    with open('HTMLReport.html', 'w') as f:
        runner = HTMLTestRunner(stream=f,
                                title='MathFunc Test Report',
                                description='generated by HTMLTestRunner.',
                                verbosity=2
                                )
        runner.run(suite)